### ISSUE TITLE
[Appliance] Add Kafka service

### ISSUE THREAD

**Issue by gtanzillo** [ManageIQ/manageiq-appliance-build#447]
Spinoff from https://github.com/ManageIQ/manageiq-appliance-build/issues/374

This should be similar to how we supply PostgreSQL out of the box on our appliance.  Basic Kafka with no HA or anything special.  If user wants an HA and/or a customized external Kafka. we should allow for that configuration as well.
- [x] Add kafka to the appliance as a RPM dependency https://github.com/ManageIQ/manageiq-rpm_build/pull/91
- [x] Bump appliance_console minimum: https://github.com/ManageIQ/manageiq-appliance/pull/310
- [x] Appliance Console work to configure and enable the services
    - Issue: https://github.com/ManageIQ/manageiq-appliance_console/issues/125
    - PR: https://github.com/ManageIQ/manageiq-appliance_console/pull/130
      ### Outstanding Issues:
      - [x]  [Investigate if logs directory should be moved to `/var/log`](https://github.com/ManageIQ/manageiq-appliance_console/issues/139) [#130 (comment)]. 
       (https://github.com/ManageIQ/manageiq-appliance_console/pull/130#discussion_r526473961)

      - [x]  [Investigate moving the persistent Kafka queue messages, to a dedicated another volume](https://github.com/ManageIQ/manageiq-appliance_console/issues/143)

      - [x]  [Investigate if there is anything else that can be done to protect the passwords on the command line](https://github.com/ManageIQ/manageiq-appliance_console/issues/140) https://github.com/ManageIQ/manageiq-appliance_console/pull/130/files#r526476752

      - [x]  [Once client configuration is complete on a server, switch Setting to `kafka`
](https://github.com/ManageIQ/manageiq-appliance_console/issues/136)
             See: https://github.com/ManageIQ/manageiq/blob/2f8ae2345eb25b16ad87f7dc124b4fe68a610bdb/config/settings.yml#L936 to `kafka`. 
             Pull Requests: [#137](https://github.com/ManageIQ/manageiq-appliance_console/pull/137) and [#20837](https://github.com/ManageIQ/manageiq/pull/20837)

      - [x] [Combine Kafka client configuration for external server and ManageIQ server](https://github.com/ManageIQ/manageiq-appliance_console/issues/135)

      - [x] [Update appliance_console CLI to enable/disable kafka](https://github.com/ManageIQ/manageiq-appliance_console/issues/142)

      - [x] [Update appliance_console  kafka client configuration to disable the kafka server](https://github.com/ManageIQ/manageiq-appliance_console/issues/141)

      - [x] [Create a kick start to build images with the kafka server pre-configured](https://github.com/ManageIQ/manageiq-appliance-build/issues/454)

      - [x] [Get Kafka configuration working with Rdkafka](https://github.com/ManageIQ/manageiq-appliance-build/issues/456)

      - [x] [Investigate how to handle Kafka's apparent dependence on hostname](https://github.com/ManageIQ/manageiq-appliance_console/issues/146)
      
### Outstanding PRs:

Should be ready to merge: https://github.com/ManageIQ/manageiq-rpm_build/pull/122
WIP: https://github.com/ManageIQ/manageiq-appliance_console/pull/137

**Comment by bdunne** [comment]
All boxes are checked.  🎉
